nclude <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <stddef.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#define RTSP_PORT 554
#define MAX_CLIENTS 10
#define BUFFER_SIZE 1024

// Function to handle each client connection
// void* handle_client(void* arg) {
//     int client_socket = *((int*)arg);
//         free(arg);  // free the allocated memory for client socket
//
//             char buffer[BUFFER_SIZE];
//                 int bytes_received;
//
//                     // Send a welcome message to the client
//                         const char *welcome_message = "RTSP/1.0 200 OK\nCSeq: 1\n\n";
//                             send(client_socket, welcome_message, strlen(welcome_message), 0);
//
//                                 // Wait for incoming RTSP requests
//                                     while ((bytes_received = recv(client_socket, buffer, sizeof(buffer) - 1, 0)) > 0) {
//                                             buffer[bytes_received] = '\0'; // Null-terminate the received data
//                                                     printf("Received RTSP request:\n%s\n", buffer);
//
//                                                             // Respond to the client based on the request type
//                                                                     if (strstr(buffer, "DESCRIBE") != NULL) {
//                                                                                 const char *response = "RTSP/1.0 200 OK\nCSeq: 2\nContent-Type: application/sdp\nContent-Length: 0\n\n";
//                                                                                             send(client_socket, response, strlen(response), 0);
//                                                                                                     } else if (strstr(buffer, "SETUP") != NULL) {
//                                                                                                                 const char *response = "RTSP/1.0 200 OK\nCSeq: 3\nTransport: RTP/AVP;unicast;client_port=8000-8001\n\n";
//                                                                                                                             send(client_socket, response, strlen(response), 0);
//                                                                                                                                     } else if (strstr(buffer, "PLAY") != NULL) {
//                                                                                                                                                 const char *response = "RTSP/1.0 200 OK\nCSeq: 4\nRange: npt=0.000-\n\n";
//                                                                                                                                                             send(client_socket, response, strlen(response), 0);
//                                                                                                                                                                     } else if (strstr(buffer, "TEARDOWN") != NULL) {
//                                                                                                                                                                                 const char *response = "RTSP/1.0 200 OK\nCSeq: 5\n\n";
//                                                                                                                                                                                             send(client_socket, response, strlen(response), 0);
//                                                                                                                                                                                                         break;
//                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                         close(client_socket);
//                                                                                                                                                                                                                             return NULL;
//                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                             // Main function to create the server and handle multiple clients
//                                                                                                                                                                                                                             int main() {
//                                                                                                                                                                                                                                 int server_socket, *new_client_socket;
//                                                                                                                                                                                                                                     struct sockaddr_in server_addr, client_addr;
//                                                                                                                                                                                                                                         socklen_t client_addr_len = sizeof(client_addr);
//                                                                                                                                                                                                                                             pthread_t thread_id;
//
//                                                                                                                                                                                                                                                 // Create a socket
//                                                                                                                                                                                                                                                     if ((server_socket = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
//                                                                                                                                                                                                                                                             perror("Socket creation failed");
//                                                                                                                                                                                                                                                                     exit(EXIT_FAILURE);
//                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                             // Set up the server address structure
//                                                                                                                                                                                                                                                                                 server_addr.sin_family = AF_INET;
//                                                                                                                                                                                                                                                                                     server_addr.sin_addr.s_addr = INADDR_ANY;
//                                                                                                                                                                                                                                                                                         server_addr.sin_port = htons(RTSP_PORT);
//
//                                                                                                                                                                                                                                                                                             // Bind the socket
//                                                                                                                                                                                                                                                                                                 if (bind(server_socket, (struct sockaddr*)&server_addr, sizeof(server_addr)) == -1) {
//                                                                                                                                                                                                                                                                                                         perror("Binding failed");
//                                                                                                                                                                                                                                                                                                                 exit(EXIT_FAILURE);
//                                                                                                                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                                                                                                                         // Listen for incoming connections
//                                                                                                                                                                                                                                                                                                                             if (listen(server_socket, MAX_CLIENTS) == -1) {
//                                                                                                                                                                                                                                                                                                                                     perror("Listening failed");
//                                                                                                                                                                                                                                                                                                                                             exit(EXIT_FAILURE);
//                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                     printf("RTSP server listening on port %d...\n", RTSP_PORT);
//
//                                                                                                                                                                                                                                                                                                                                                         // Accept incoming connections and spawn a new thread for each client
//                                                                                                                                                                                                                                                                                                                                                             while (1) {
//                                                                                                                                                                                                                                                                                                                                                                     new_client_socket = malloc(sizeof(int));  // Allocate memory for new socket
//                                                                                                                                                                                                                                                                                                                                                                             *new_client_socket = accept(server_socket, (struct sockaddr*)&client_addr, &client_addr_len);
//                                                                                                                                                                                                                                                                                                                                                                                     if (*new_client_socket == -1) {
//                                                                                                                                                                                                                                                                                                                                                                                                 perror("Accept failed");
//                                                                                                                                                                                                                                                                                                                                                                                                             free(new_client_socket);
//                                                                                                                                                                                                                                                                                                                                                                                                                         continue;
//                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                         // Create a new thread to handle the client
//                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (pthread_create(&thread_id, NULL, handle_client, (void*)new_client_socket) != 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             perror("Thread creation failed");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                         close(*new_client_socket);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     free(new_client_socket);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         pthread_detach(thread_id);  // Detach thread to free resources automatically
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         close(server_socket);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return 0;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
