#include <stdio.h>
#include <stdlib.h>
#include<stddef.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>
#include <gst/gst.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netdb.h>

// Define the RTSP URL (for example, rtsp://152.228.142.4:5327/video5327)
// #define RTSP_URL "rtsp://152.228.142.4:5327/video5327"
//
// // Function to create and connect a socket to the RTSP server
// int create_rtsp_socket(const char *url) {
//     int sock;
//         struct sockaddr_in server_addr;
//             struct hostent *host;
//                 char *host_ip;
//                     unsigned short port = 5327; // Default port for RTSP stream
//
//                         // Extract host and port from RTSP URL
//                             char *hostname = strstr(url, "://") + 3; // Skip 'rtsp://'
//                                 char *port_str = strstr(hostname, ":");
//                                     if (port_str) {
//                                             *port_str = '\0';
//                                                     port = atoi(port_str + 1);
//                                                         }
//
//                                                             host = gethostbyname(hostname);
//                                                                 if (!host) {
//                                                                         perror("Unable to resolve host");
//                                                                                 return -1;
//                                                                                     }
//
//                                                                                         host_ip = inet_ntoa(*(struct in_addr *)host->h_addr);
//
//                                                                                             // Create socket
//                                                                                                 sock = socket(AF_INET, SOCK_STREAM, 0);
//                                                                                                     if (sock < 0) {
//                                                                                                             perror("Unable to create socket");
//                                                                                                                     return -1;
//                                                                                                                         }
//
//                                                                                                                             // Set up the server address
//                                                                                                                                 memset(&server_addr, 0, sizeof(server_addr));
//                                                                                                                                     server_addr.sin_family = AF_INET;
//                                                                                                                                         server_addr.sin_port = htons(port);
//                                                                                                                                             server_addr.sin_addr.s_addr = inet_addr(host_ip);
//
//                                                                                                                                                 // Connect to the RTSP server
//                                                                                                                                                     if (connect(sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0) {
//                                                                                                                                                             perror("Unable to connect to RTSP server");
//                                                                                                                                                                     return -1;
//                                                                                                                                                                         }
//
//                                                                                                                                                                             return sock;
//                                                                                                                                                                             }
//
//                                                                                                                                                                             // Function to send RTSP DESCRIBE command to get the stream information
//                                                                                                                                                                             void send_rtsp_describe(int sock) {
//                                                                                                                                                                                 char request[1024];
//                                                                                                                                                                                     snprintf(request, sizeof(request),
//                                                                                                                                                                                                  "DESCRIBE rtsp://152.228.142.4:5327/video5327 RTSP/1.0\r\n"
//                                                                                                                                                                                                               "CSeq: 1\r\n"
//                                                                                                                                                                                                                            "User-Agent: CustomRTSPClient/1.0\r\n\r\n");
//                                                                                                                                                                                                                                send(sock, request, strlen(request), 0);
//                                                                                                                                                                                                                                }
//
//                                                                                                                                                                                                                                // Function to send RTSP SETUP command for session setup
//                                                                                                                                                                                                                                void send_rtsp_setup(int sock) {
//                                                                                                                                                                                                                                    char request[1024];
//                                                                                                                                                                                                                                        snprintf(request, sizeof(request),
//                                                                                                                                                                                                                                                     "SETUP rtsp://152.228.142.4:5327/video5327/trackID=1 RTSP/1.0\r\n"
//                                                                                                                                                                                                                                                                  "CSeq: 2\r\n"
//                                                                                                                                                                                                                                                                               "Transport: RTP/AVP;unicast;client_port=8000-8001\r\n"
//                                                                                                                                                                                                                                                                                            "User-Agent: CustomRTSPClient/1.0\r\n\r\n");
//                                                                                                                                                                                                                                                                                                send(sock, request, strlen(request), 0);
//                                                                                                                                                                                                                                                                                                }
//
//                                                                                                                                                                                                                                                                                                // Function to send RTSP PLAY command to start streaming
//                                                                                                                                                                                                                                                                                                void send_rtsp_play(int sock) {
//                                                                                                                                                                                                                                                                                                    char request[1024];
//                                                                                                                                                                                                                                                                                                        snprintf(request, sizeof(request),
//                                                                                                                                                                                                                                                                                                                     "PLAY rtsp://152.228.142.4:5327/video5327 RTSP/1.0\r\n"
//                                                                                                                                                                                                                                                                                                                                  "CSeq: 3\r\n"
//                                                                                                                                                                                                                                                                                                                                               "Range: npt=0.000-\r\n"
//                                                                                                                                                                                                                                                                                                                                                            "User-Agent: CustomRTSPClient/1.0\r\n\r\n");
//                                                                                                                                                                                                                                                                                                                                                                send(sock, request, strlen(request), 0);
//                                                                                                                                                                                                                                                                                                                                                                }
//
//                                                                                                                                                                                                                                                                                                                                                                // Function to check the status of the stream (whether it's recording or not)
//                                                                                                                                                                                                                                                                                                                                                                void *check_stream_status(void *arg) {
//                                                                                                                                                                                                                                                                                                                                                                    int sock = *(int *)arg;
//                                                                                                                                                                                                                                                                                                                                                                        char response[4096];
//                                                                                                                                                                                                                                                                                                                                                                            int ret;
//
//                                                                                                                                                                                                                                                                                                                                                                                // Send DESCRIBE to the RTSP server and check the response
//                                                                                                                                                                                                                                                                                                                                                                                    send_rtsp_describe(sock);
//                                                                                                                                                                                                                                                                                                                                                                                        ret = recv(sock, response, sizeof(response), 0);
//                                                                                                                                                                                                                                                                                                                                                                                            if (ret < 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                    perror("Failed to receive response from RTSP server");
//                                                                                                                                                                                                                                                                                                                                                                                                            return NULL;
//                                                                                                                                                                                                                                                                                                                                                                                                                }
//                                                                                                                                                                                                                                                                                                                                                                                                                    response[ret] = '\0';
//                                                                                                                                                                                                                                                                                                                                                                                                                        printf("RTSP Server Response: %s\n", response);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                            // Check for 'OK' in response to confirm stream info
//                                                                                                                                                                                                                                                                                                                                                                                                                                if (strstr(response, "OK")) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Stream is available.\n");
//                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Stream is not available or discontinued.\n");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                            return NULL;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Function to initialize and run the GStreamer pipeline
//                                                                                                                                                                                                                                                                                                                                                                                                                                                            void *run_gst_pipeline(void *arg) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                GstElement *pipeline, *source, *decoder, *sink;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GstBus *bus;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                        GstMessage *msg;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Initialize GStreamer
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gst_init(NULL, NULL);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Create the GStreamer pipeline
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pipeline = gst_pipeline_new("rtsp-pipeline");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            source = gst_element_factory_make("rtspsrc", "source");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoder = gst_element_factory_make("decodebin", "decoder");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sink = gst_element_factory_make("autovideosink", "sink");
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!pipeline || !source || !decoder || !sink) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fprintf(stderr, "Failed to create elements.\n");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NULL;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Set the source location (RTSP URL)
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    g_object_set(G_OBJECT(source), "location", RTSP_URL, NULL);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Link the elements in the pipeline
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gst_bin_add_many(GST_BIN(pipeline), source, decoder, sink, NULL);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gst_element_link(source, decoder);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gst_element_link(decoder, sink);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Watch for messages on the bus
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bus = gst_element_get_bus(pipeline);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gst_bus_add_watch(bus, (GstBusFunc)gst_bus_async_signal_func, NULL);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Start the pipeline
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gst_element_set_state(pipeline, GST_STATE_PLAYING);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("GStreamer pipeline is now playing the stream...\n");
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Wait for the stream to finish or an error
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    msg = gst_bus_poll(bus, GST_MESSAGE_ERROR | GST_MESSAGE_EOS, GST_CLOCK_TIME_NONE);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (msg != NULL) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gst_message_unref(msg);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Stop the pipeline and cleanup
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gst_element_set_state(pipeline, GST_STATE_NULL);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gst_object_unref(bus);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gst_object_unref(pipeline);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NULL;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int main(int argc, const char *argv[]) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int rtsp_socket;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pthread_t status_thread, gst_thread;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Create the socket connection to the RTSP server
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rtsp_socket = create_rtsp_socket(RTSP_URL);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (rtsp_socket < 0) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fprintf(stderr, "Failed to connect to RTSP server.\n");
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return -1;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Create a thread to check stream status
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pthread_create(&status_thread, NULL, check_stream_status, &rtsp_socket);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Create a thread to run the GStreamer pipeline
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pthread_create(&gst_thread, NULL, run_gst_pipeline, NULL);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Wait for both threads to finish
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pthread_join(status_thread, NULL);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pthread_join(gst_thread, NULL);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Close the socket
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    close(rtsp_socket);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
//
